application: nadderud-no
version: 1
runtime: python27
threadsafe: true

handlers:
  - url: /static/.*
    static_dir: templates/static

  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /admin.*
    script: admin.app
    login: required
    secure: always

  - url: /.*
    script: website.app

libraries:
  - name: webapp2
    version: "2.5.2"
  - name: jinja2
    version: "2.6"
