application: nadderud-no
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /nadderud/.*
  script: main.app

- url: /admin/.*
  script: admin.app
  login: admin

- url: /.*
  script: manage.app
  login: required
